#!/bin/bash

cd /var/mobile/ipadkid358
rm Packages.bz2
ls debs | while read d
do
p=debs/"$d"
dpkg-deb -f $p >> Packages
echo "Filename: $p" >> Packages
echo "MD5sum: $(md5sum $p | cut -d " " -f1)" >> Packages
echo "Size: $(stat -c %s $p)" >> Packages
echo >> Packages
done
bzip2 -z Packages
git add --all
test "$1" = "" && git commit -m Update || git commit -m "$1"
git push