#!/bin/bash

cd /var/mobile/ipadkid358/piracy;
rm Packages.bz2;
bzip2 -z Packages;
cd /var/mobile/ipadkid358;
rm Packages.bz2;
bzip2 -z Packages;
cd /var/mobile/ipadkid358;
git add --all;
git commit -m "Update";
git push 